import type { Food } from './types';

export const defaultFoods: Food[] = [
  {
    id: 'apple',
    category: 'fruit',
    serving_size_g: 100,
    calories: 52,
    protein: 0.3,
    carbohydrates: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10,
    name: { en: 'Apple', it: 'Mela' },
  },
  {
    id: 'banana',
    category: 'fruit',
    serving_size_g: 100,
    calories: 89,
    protein: 1.1,
    carbohydrates: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12,
    name: { en: 'Banana', it: 'Banana' },
  },
  {
    id: 'chicken-breast',
    category: 'meat',
    serving_size_g: 100,
    calories: 165,
    protein: 31,
    carbohydrates: 0,
    fat: 3.6,
    name: { en: 'Chicken Breast', it: 'Petto di Pollo' },
  },
  {
    id: 'salmon',
    category: 'fish',
    serving_size_g: 100,
    calories: 208,
    protein: 20,
    carbohydrates: 0,
    fat: 13,
    name: { en: 'Salmon', it: 'Salmone' },
  },
  {
    id: 'rice',
    category: 'grain',
    serving_size_g: 100,
    calories: 130,
    protein: 2.7,
    carbohydrates: 28,
    fat: 0.3,
    name: { en: 'White Rice', it: 'Riso Bianco' },
  },
  {
    id: 'broccoli',
    category: 'vegetable',
    serving_size_g: 100,
    calories: 34,
    protein: 2.8,
    carbohydrates: 7,
    fat: 0.4,
    fiber: 2.6,
    name: { en: 'Broccoli', it: 'Broccoli' },
  },
  {
    id: 'spinach',
    category: 'vegetable',
    serving_size_g: 100,
    calories: 23,
    protein: 2.9,
    carbohydrates: 3.6,
    fat: 0.4,
    fiber: 2.2,
    name: { en: 'Spinach', it: 'Spinaci' },
  },
  {
    id: 'almonds',
    category: 'nuts',
    serving_size_g: 100,
    calories: 579,
    protein: 21,
    carbohydrates: 22,
    fat: 49,
    fiber: 12.5,
    name: { en: 'Almonds', it: 'Mandorle' },
  },
  {
    id: 'egg',
    category: 'dairy_and_alternatives',
    serving_size_g: 100,
    calories: 155,
    protein: 13,
    carbohydrates: 1.1,
    fat: 11,
    name: { en: 'Egg', it: 'Uovo' },
  },
  {
    id: 'oats',
    category: 'grain',
    serving_size_g: 100,
    calories: 389,
    protein: 16.9,
    carbohydrates: 66.3,
    fat: 6.9,
    fiber: 10.6,
    name: { en: 'Oats', it: 'Avena' },
  },
  {
    id: 'beef',
    category: 'meat',
    serving_size_g: 100,
    calories: 250,
    protein: 26,
    carbohydrates: 0,
    fat: 15,
    name: { en: 'Ground Beef (85/15)', it: 'Carne Macinata (85/15)' },
  },
  {
    id: 'potatoes',
    category: 'vegetable',
    serving_size_g: 100,
    calories: 77,
    protein: 2,
    carbohydrates: 17,
    fat: 0.1,
    fiber: 2.2,
    name: { en: 'Potatoes', it: 'Patate' },
  },
  {
    id: 'greek-yogurt',
    category: 'dairy_and_alternatives',
    serving_size_g: 100,
    calories: 59,
    protein: 10,
    carbohydrates: 3.6,
    fat: 0.4,
    sugar: 3.2,
    name: { en: 'Greek Yogurt', it: 'Yogurt Greco' },
  },
  {
    id: 'olive-oil',
    category: 'fats_and_oils',
    serving_size_g: 100,
    calories: 884,
    protein: 0,
    carbohydrates: 0,
    fat: 100,
    name: { en: 'Olive Oil', it: 'Olio d\'oliva' },
  },
  {
    id: 'quinoa',
    category: 'grain',
    serving_size_g: 100,
    calories: 120,
    protein: 4.4,
    carbohydrates: 21.3,
    fat: 1.9,
    fiber: 2.8,
    name: { en: 'Quinoa', it: 'Quinoa' },
  },
];
