import type { Food } from './types';

export const defaultFoods: Food[] = [
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruit',
    serving_size_g: 100,
    calories: 52,
    protein: 0.3,
    carbohydrates: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10,
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruit',
    serving_size_g: 100,
    calories: 89,
    protein: 1.1,
    carbohydrates: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12,
  },
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    category: 'Meat',
    serving_size_g: 100,
    calories: 165,
    protein: 31,
    carbohydrates: 0,
    fat: 3.6,
  },
  {
    id: 'salmon',
    name: 'Salmon',
    category: 'Fish',
    serving_size_g: 100,
    calories: 208,
    protein: 20,
    carbohydrates: 0,
    fat: 13,
  },
  {
    id: 'rice',
    name: 'White Rice',
    category: 'Grain',
    serving_size_g: 100,
    calories: 130,
    protein: 2.7,
    carbohydrates: 28,
    fat: 0.3,
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'Vegetable',
    serving_size_g: 100,
    calories: 34,
    protein: 2.8,
    carbohydrates: 7,
    fat: 0.4,
    fiber: 2.6,
  },
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'Vegetable',
    serving_size_g: 100,
    calories: 23,
    protein: 2.9,
    carbohydrates: 3.6,
    fat: 0.4,
    fiber: 2.2,
  },
  {
    id: 'almonds',
    name: 'Almonds',
    category: 'Nuts',
    serving_size_g: 100,
    calories: 579,
    protein: 21,
    carbohydrates: 22,
    fat: 49,
    fiber: 12.5,
  },
  {
    id: 'egg',
    name: 'Egg',
    category: 'Dairy & Alternatives',
    serving_size_g: 100,
    calories: 155,
    protein: 13,
    carbohydrates: 1.1,
    fat: 11,
  },
  {
    id: 'oats',
    name: 'Oats',
    category: 'Grain',
    serving_size_g: 100,
    calories: 389,
    protein: 16.9,
    carbohydrates: 66.3,
    fat: 6.9,
    fiber: 10.6,
  },
  {
    id: 'beef',
    name: 'Ground Beef (85/15)',
    category: 'Meat',
    serving_size_g: 100,
    calories: 250,
    protein: 26,
    carbohydrates: 0,
    fat: 15,
  },
  {
    id: 'potatoes',
    name: 'Potatoes',
    category: 'Vegetable',
    serving_size_g: 100,
    calories: 77,
    protein: 2,
    carbohydrates: 17,
    fat: 0.1,
    fiber: 2.2,
  },
  {
    id: 'greek-yogurt',
    name: 'Greek Yogurt',
    category: 'Dairy & Alternatives',
    serving_size_g: 100,
    calories: 59,
    protein: 10,
    carbohydrates: 3.6,
    fat: 0.4,
    sugar: 3.2,
  },
  {
    id: 'olive-oil',
    name: 'Olive Oil',
    category: 'Fats & Oils',
    serving_size_g: 100,
    calories: 884,
    protein: 0,
    carbohydrates: 0,
    fat: 100,
  },
  {
    id: 'quinoa',
    name: 'Quinoa',
    category: 'Grain',
    serving_size_g: 100,
    calories: 120,
    protein: 4.4,
    carbohydrates: 21.3,
    fat: 1.9,
    fiber: 2.8,
  },
];
